# Generated by Django 4.2.13 on 2024-07-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='category_images/%Y/%m/%d/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mantaghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('shomare_shaba', models.CharField(max_length=26)),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=555)),
                ('post_code', models.CharField(max_length=10)),
                ('parvane_kasb', models.FileField(upload_to='parvane_kast__<django.db.models.fields.CharField>/%Y/%m/%d/')),
                ('tasvire_personely', models.ImageField(upload_to='tasvire_personely__<django.db.models.fields.CharField>/%Y/%m/%d/')),
                ('kart_melli', models.ImageField(upload_to='kart_melli__<django.db.models.fields.CharField>/%Y/%m/%d/')),
                ('shenasname', models.ImageField(upload_to='tasvire_shenasname__<django.db.models.fields.CharField>/%Y/%m/%d/')),
                ('logo', models.ImageField(upload_to='logo__<django.db.models.fields.CharField>/%Y/%m/%d/')),
                ('roozname_rasmi_alamat', models.FileField(upload_to='roozname_rasmi_alamat__<django.db.models.fields.CharField>/%Y/%m/%d/')),
                ('gharardad', models.FileField(upload_to='gharardad__<django.db.models.fields.CharField>/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.city')),
                ('mantaghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.mantaghe')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.province')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_type', to='store.categoryproduct')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_type', to='store.subcategoryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_farsi', models.CharField(max_length=255)),
                ('title_english', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('product_code', models.CharField(max_length=100)),
                ('product_model', models.CharField(max_length=255)),
                ('status_originaly', models.CharField(choices=[('o', 'اصل ، اوریجینال')], max_length=10)),
                ('product_warranty', models.BooleanField()),
                ('sending_method', models.CharField(choices=[('pish', 'پیشتاز'), ('tip', 'تیپاکس'), ('bar', 'باربری'), ('peyk', 'پیک موتوری')], max_length=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.categoryproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subcategoryproduct')),
            ],
        ),
    ]
