# Generated by Django 4.2.13 on 2024-07-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
