# Generated by Django 4.2.13 on 2024-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
