# Generated by Django 4.2.13 on 2024-07-15 15:47

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(default=store.models.random_code, max_length=6, unique=True),
        ),
    ]
