# Generated by Django 4.2.13 on 2024-07-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_baseproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='description',
            field=models.TextField(),
        ),
    ]
