# Generated by Django 4.2.13 on 2024-07-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lists', to='store.baseproduct'),
        ),
    ]
