# Generated by Django 4.2.13 on 2024-07-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='product_list_code',
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.producttype'),
        ),
    ]
