# Generated by Django 4.2.13 on 2024-07-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_baseproduct_product_list_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='product_status',
            field=models.CharField(choices=[('c', 'تایید شده'), ('w', 'در انتظار تایید'), ('n', 'تایید نشده')], default='w', max_length=1),
        ),
    ]
