# Generated by Django 4.2.13 on 2024-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status_originaly',
            field=models.CharField(choices=[('o', 'Original')], max_length=10),
        ),
    ]
