# Generated by Django 4.2.13 on 2024-07-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_baseproduct_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='base_product',
        ),
    ]
