# Generated by Django 4.2.13 on 2024-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_status_originaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sending_method',
            field=models.CharField(choices=[('pish', 'پیشتاز'), ('tip', 'تیپاکس'), ('bar', 'باربری'), ('peyk', 'پیک موتوری')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='status_originaly',
            field=models.CharField(choices=[('o', 'اصل ، اوریجینال')], max_length=10),
        ),
    ]
