# Generated by Django 4.2.13 on 2024-07-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_package',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_package',
            field=models.IntegerField(null=True),
        ),
    ]
