# Generated by Django 4.2.13 on 2024-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_height_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_package',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
