# Generated by Django 4.2.13 on 2024-07-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_length_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField()),
                ('time_until', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='receiver_full_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='refferer_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='store.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='code_posti',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mahalle',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mantaghe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='store.mantaghe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='pelak',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='store.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='recevier_mobile',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='vahed',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='store.timeorder')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='date_time_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.dateorder'),
            preserve_default=False,
        ),
    ]
