# Generated by Django 4.2.13 on 2024-07-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_timeorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateorder',
            name='time',
        ),
        migrations.AddField(
            model_name='dateorder',
            name='time',
            field=models.ManyToManyField(related_name='dates', to='store.timeorder'),
        ),
    ]
