# Generated by Django 4.2.13 on 2024-07-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_date_time_order_order_date_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPhotografy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('store_name', models.CharField(max_length=255)),
                ('request_text', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_photografy', to='store.city')),
                ('mantaghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_photografy', to='store.mantaghe')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_photografy', to='store.province')),
            ],
        ),
    ]
