# Generated by Django 4.2.13 on 2024-07-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
