# Generated by Django 4.2.13 on 2024-07-17 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 19, 39, 31, 505406, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 19, 42, 31, 505406, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
