# Generated by Django 4.2.13 on 2024-07-17 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_otprequest_valid_from_otprequest_valid_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otprequest',
            old_name='code',
            new_name='otp_code',
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 19, 42, 10, 272627, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 19, 45, 10, 272627, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
