# Generated by Django 4.2.13 on 2024-07-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_rename_product_product_base_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('m', 'مرد'), ('f', 'زن')], max_length=1)),
                ('code_melli', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('madrak_grade', models.CharField(choices=[('di', 'دیپلم'), ('fd', 'فوق دیپلم'), ('li', 'لیسانس'), ('fl', 'فوق لیسانس'), ('do', 'دکترا')], max_length=2)),
                ('nezam_vazife_status', models.CharField(choices=[('m', 'معاف'), ('a', 'اتمام خدمت')], max_length=3)),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=600)),
                ('post_code', models.CharField(max_length=10)),
                ('img_personelly', models.ImageField(upload_to='admin_panel/staffs/img_personelly/%Y/%m/%d/')),
                ('kart_melli', models.ImageField(upload_to='admin_panel/staffs/kart_melli/%Y/%m/%d/')),
                ('shenasname', models.ImageField(upload_to='admin_panel/staffs/shenasname/%Y/%m/%d/')),
                ('img_madrak', models.ImageField(upload_to='admin_panel/staffs/img_madrak/%Y/%m/%d/')),
                ('police_clearance', models.ImageField(upload_to='admin_panel/staffs/police_clearance/%Y/%m/%d/')),
                ('payan_khedmat_img', models.ImageField(upload_to='admin_panel/staffs/payan_khedmat_img/%Y/%m/%d/')),
                ('english_status', models.CharField(choices=[('vg', 'خیلی خوب'), ('g', 'خوب')], max_length=2)),
                ('computer_icdl_status', models.CharField(choices=[('vg', 'خیلی خوب'), ('g', 'خوب')], max_length=2)),
                ('accounting', models.CharField(choices=[('vg', 'خیلی خوب'), ('g', 'خوب')], max_length=2)),
                ('digital_marketing', models.CharField(choices=[('vg', 'خیلی خوب'), ('g', 'خوب')], max_length=2)),
                ('photo_and_movie_skills', models.CharField(choices=[('vg', 'خیلی خوب'), ('g', 'خوب')], max_length=2)),
                ('areas_of_cooperation', models.CharField(max_length=25)),
                ('working_conditions', models.CharField(max_length=555)),
                ('minimum_salary_requested', models.IntegerField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.city')),
                ('mantaghe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.mantaghe')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.province')),
            ],
        ),
    ]
