# Generated by Django 4.2.13 on 2024-07-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_staff_nezam_vazife_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('web_mail', 'you can access to web mail page')]},
        ),
    ]
